version: '3.8'

services:
  rstudio:
    image: rocker/rstudio
    container_name: rstudio
    ports:
      - "8787:8787"
    environment:
      - PASSWORD=Bot@5063
    volumes:
      - ./:/home/rstudio

